version: '3.8'
services:
  neo4j:
    image: neo4j:5.18
    container_name: neo4j_faq
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol
    volumes:
      - ./neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password123 # 设置用户名和密码
      - NEO4J_PLUGINS=["apoc"] # 启用 APOC 插件